---
include:
  - board: rpi_pico
    shield: phenom_mini_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    keymap: velvet_v3
    artifact-name: phenom_mini_left
  - board: rpi_pico
    shield: phenom_mini_right
    artifact-name: phenom_mini_right_83hz
    keymap: velvet_v3
    cmake-args: >-
      -DCONFIG_EH_PMW3610_ALT_MODE=y
      -DCONFIG_ZMK_USB_LOGGING=n
      -DCONFIG_EH_PMW3610_ALT_FORCE_AWAKE_4MS_MODE=y
      -DCONFIG_EH_PMW3610_ALT_REPORT_INTERVAL_MS=12
  - board: rpi_pico
    shield: phenom_mini_right
    artifact-name: phenom_mini_right_200hz
    keymap: velvet_v3
    cmake-args: >-
      -DCONFIG_EH_PMW3610_ALT_MODE=y
      -DCONFIG_ZMK_USB_LOGGING=n
      -DCONFIG_EH_PMW3610_ALT_FORCE_AWAKE_4MS_MODE=y
      -DCONFIG_EH_PMW3610_ALT_REPORT_INTERVAL_MS=0
  - board: rpi_pico
    shield: phenom_mini_right
    artifact-name: phenom_mini_right_fseg_v024
    keymap: velvet_v3
    cmake-args: >-
      -DCONFIG_EH_PMW3610_FSEGMENT=y
      -DCONFIG_EH_PMW3610_FSEG_DROP=1
      -DCONFIG_EH_PMW3610_FSEG_SYNTH=y
      -DCONFIG_EH_PMW3610_FSEG_SYNTH_MAX=12
      -DCONFIG_EH_PMW3610_FSEG_SYNTH_MAXCONSEC=8
      -DCONFIG_EH_PMW3610_FSEG_SYNTH_MIN_MAG=3
      -DCONFIG_EH_PMW3610_FSEG_REVOTE=y
      -DCONFIG_EH_PMW3610_FSEG_REVOTE_MAG=10
      -DCONFIG_EH_PMW3610_FSEG_REFMAG=5
      -DCONFIG_EH_PMW3610_FSEG_REVERSE=12
      -DCONFIG_EH_PMW3610_FSEG_FAST_MAG=6
      -DCONFIG_EH_PMW3610_FSEG_FAST_WIN_MS=100
      -DCONFIG_EH_PMW3610_FSEG_PASSMIN_CONFIRM=y
      -DCONFIG_EH_PMW3610_FSEG_PASSMIN_WIN_MS=100
      -DCONFIG_EH_PMW3610_VECT=y
      -DCONFIG_EH_PMW3610_VECT_SYNN=y
      -DCONFIG_EH_PMW3610_VECT_QGATE=4
      -DCONFIG_EH_PMW3610_VECT_WIN_MS=600
      -DCONFIG_EH_PMW3610_POLL_INTERVAL_MS=5
      -DCONFIG_EH_PMW3610_MOTION_TRACE=y
      -DCONFIG_EH_PMW3610_MOTION_TRACE_MAX=40000
      -DCONFIG_ZMK_USB_LOGGING=n
      -DCONFIG_ZMK_LOGGING_MINIMAL=y
      -DCONFIG_LOG_DEFAULT_LEVEL=1
  # - board: rpi_pico
  #   shield: ergohaven_hpd_v2_left
  #   cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
  #   keymap: ergohaven_hpd_v2
  #   artifact-name: ergohaven_hpd_v2_left
  # - board: rpi_pico
  #   shield: ergohaven_hpd_v2_right
  #   artifact-name: ergohaven_hpd_v2_right
  #   keymap: ergohaven_hpd_v2

  # - board: ergohaven
  #   shield: velvet_v3_left

  # - board: ergohaven
  #   shield: velvet_v3_right
  # - board: ergohaven
  #   shield: velvet_v3_qube qube dongle_screen
  #   artifact-name: velvet_v3_qube-ergohaven-zmk

  # - board: ergohaven
  #   shield: velvet_v3_left_qube
    


  # - board: ergohaven
  #   shield: op36_left

  # - board: ergohaven
  #   shield: op36_right

#####№##

    
  # - board: ergohaven
  #   shield: k03_left
  #   keymap: k03_ruen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: k03_left_ruen-ergohaven-zmk
  # - board: ergohaven
  #   shield: k03_right
  # - board: ergohaven
  #   shield: k03_qube qube dongle_screen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: k03_qube-ergohaven-zmk
  # - board: ergohaven
  #   shield: k03_qube qube dongle_screen
  #   keymap: k03_ruen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: k03_qube_ruen-ergohaven-zmk
  # - board: ergohaven
  #   shield: k03_left_qube

  # - board: ergohaven
  #   shield: imperial44_left
  #   snippet: studio-rpc-usb-uart
  # - board: ergohaven
  #   shield: imperial44_left
  #   keymap: imperial44_ruen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: imperial44_left_ruen-ergohaven-zmk
  # - board: ergohaven
  #   shield: imperial44_right
  # - board: ergohaven
  #   shield: imperial44_qube qube dongle_screen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: imperial44_qube-ergohaven-zmk
  # - board: ergohaven
  #   shield: imperial44_qube qube dongle_screen
  #   keymap: imperial44_ruen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: imperial44_qube_ruen-ergohaven-zmk
  # - board: ergohaven
  #   shield: imperial44_left_qube

  # - board: ergohaven
  #   shield: trackball
  #   snippet: studio-rpc-usb-uart
    # - board: ergohaven
  #   shield: velvet_v3_left
  #   keymap: velvet_v3_ruen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: velvet_v3_left_ruen-ergohaven-zmk
    # - board: ergohaven
  #   shield: velvet_v3_qube qube dongle_screen
  #   keymap: velvet_v3_ruen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: velvet_v3_qube_ruen-ergohaven-zmk
    # - board: ergohaven
  #   shield: op36_ruen op36_left
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: op36_left_ruen-ergohaven-zmk
    # - board: ergohaven
  #   shield: op36_qube qube dongle_screen # or prospector_adapter
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: op36_qube-ergohaven-zmk
  # - board: ergohaven
  #   shield: op36_left_qube
    # - board: ergohaven
  #   shield: velvet_v3_ui_left
  # # - board: ergohaven
  # #   shield: velvet_v3_ui_right
  # #   keymap: velvet_v3_ui_ruen
  # #   snippet: studio-rpc-usb-uart
  # #   artifact-name: velvet_v3_ui_right_ruen-ergohaven-zmk
  # # - board: ergohaven
  # #   shield: velvet_v3_ui_right
  # #   keymap: velvet_v3_ui_ruen
  # #   snippet: studio-rpc-usb-uart
  # #   artifact-name: velvet_v3_ui_right_ruen-ergohaven-zmk
  # - board: ergohaven
  #   shield: velvet_v3_ui_right
  #   snippet: studio-rpc-usb-uart
  # # - board: ergohaven
  # #   shield: velvet_v3_ui_qube qube dongle_screen
  # #   snippet: studio-rpc-usb-uart
  # #   artifact-name: velvet_v3_ui_qube-ergohaven-zmk
  # # - board: ergohaven
  # #   shield: velvet_v3_ui_qube qube dongle_screen
  # #   keymap: velvet_v3_ui_ruen
  # #   snippet: studio-rpc-usb-uart
  # - board: ergohaven
  #   shield: velvet_v3_ui_qube qube dongle_screen
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: velvet_v3_ui_qube-ergohaven-zmk
  # # - board: ergohaven
  # #   shield: velvet_v3_ui_qube qube dongle_screen
  # #   keymap: velvet_v3_ui_ruen
  # #   snippet: studio-rpc-usb-uart
  # #   artifact-name: velvet_v3_ui_qube_ruen-ergohaven-zmk
  # - board: ergohaven
  #   shield: velvet_v3_ui_right_qube

  # - board: ergohaven
  #   shield: settings_reset
