CONFIG_ZMK_SPLIT=y

CONFIG_ZMK_MACRO_DEFAULT_WAIT_MS=10
CONFIG_USB_HID_POLL_INTERVAL_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

CONFIG_ZMK_BLE=n
CONFIG_BT=n
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
