manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com/ergohaven
    - name: wanyann
      url-base: https://github.com/wanyann
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov  
    - name: amgskobo
      url-base: https://github.com/amgskobo
  projects:
    - name: ergohaven-zmk
      remote: wanyann
      revision: main
      import: config/west.yml
    - name: zmk-pointing-acceleration
      remote: oleksandrmaslov
      revision: main
    - name: zmk-input-inertia
      remote: wanyann
      revision: main
    - name: zmk-sm-td
      remote: wanyann
      revision: main
  self:
    path: config
