manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/nmunnich
    - name: ergohaven
      url-base: https://github.com/ergohaven
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: ssbb
      url-base: https://github.com/ssbb
    - name: nmunnich
      url-base: https://github.com/nmunnich
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: layer-locking
      import: app/west.yml
    - name: ergohaven-zmk
      remote: ergohaven
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-antecedent-morph
      remote: ssbb
      revision: v1
  self:
    path: config
