# Включаем режим Split-клавиатуры
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_TRANSPORT_SERIAL=y

# Настройки USB (VID/PID из вашего QMK config)
CONFIG_ZMK_USB=y
CONFIG_ZMK_HID_VENDOR_ID=0xE126
CONFIG_ZMK_HID_PRODUCT_ID=0x0051

